[project]
name = "vocadb-scripts"
version = "1.1.0"
description = "Collection of VocaDB related scripts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "vdbpy",
]

[tool.uv.sources]
vdbpy = { git = "https://github.com/Shiroizu/VDBpy" }
